### ISSUE TITLE
Off by one errors in percentile?

### ISSUE THREAD

**Issue by diazrenata** [diazrenata/scadsanalysis#35]
If you have found 100% of the feasible set, can you have a percentile value of 0 or 100? 

ugh, percentiles are actually kind of sketchily defined at the edges. You can have 100 (value = max(values)), but I think not 0. There is the potential for odd edge behavior.

**Comment by diazrenata** [comment]
If you have found 100% of the feasible set you are in a categorically different situation than if you have found less than 100% of the feasible set.

If you have found every element, it is possible to say the proportion of values <= obs = 100, if it is the maximum value. Similarly, we can know the precise proportion of values <= obs for any obs.

If you have not found every element, you can only say that the proportion of values <= obs = nsamples / nsamples + 1. This is because in that situation you are splitting a space bounded only by +- Inf into nsamples + 1 pieces. At the other end, you can only say that the proportion of values <= obs = 1 / nsamples+1. If we draw 10 samples, we have split the line into 11 pieces. The samples are uniformly distributed, so the 11 pieces are equal. If our new focal point is below or above the min/max breakpoint, all we know is that we are in the bottom/top 11th. 

You also cannot be wholly precise about the intermediate percentiles. We can only know that a value is somewhere between the 10 and 20%, if we have 10 samples for example. If an obs value lands exactly on a sample value, we're still not *really* confident in it, because the samples are samples.

**Comment by ha0ye** [comment]
This sounds similar to p-values for randomization tests. The formula I fall back on is p = (k+1)/(n+1), where k is the number of values from the null distribution that are more extreme than the test statistic, and n is the number of samples (the size of the null distribution).

This addresses the edge case scenario where the test statistic is more extreme than all the samples in the null distribution; this formula yields p = 1/(n+1), which is nice in being < 1/n, but also not 0 (which is nonsensical.
